version: "3.5"
services:
    app1:
      image: "infracloudio/csvserver:latest"
      volumes:
        - ${PWD}/inputFile:/csvserver/inputdata
      ports:
        - 9393:9300
      environment:
         CSVSERVER_BORDER: "Orange"
      networks:
        - internal

networks:
   internal:

