version: "3.5"
services:
    app1:
      image: "infracloudio/csvserver:latest"
      volumes:
        - ${PWD}/inputFile:/csvserver/inputdata
      ports:
        - 9393:9300
      environment:
         CSVSERVER_BORDER: "Orange"
      networks:
        - internal

    promethus:
      image: "prom/prometheus:v2.22.0"
      volumes:
        - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
      networks:
        - internal

networks:
   internal:

